// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OICAR.Models;

[Table("CartItem")]
public partial class CartItem
{
    [Key]
    [Column("IDCartItem")]
    public int IdcartItem { get; set; }

    [Column("CartID")]
    public int CartId { get; set; }

    [Column("ItemID")]
    public int ItemId { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("CartId")]
    [InverseProperty("CartItems")]
    public virtual Cart Cart { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("CartItems")]
    public virtual Item Item { get; set; }
}