// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OICAR.Models;

[Table("OrderItem")]
public partial class OrderItem
{
    [Key]
    [Column("IDOrderItem")]
    public int IdorderItem { get; set; }

    [Column("OrderID")]
    public int OrderId { get; set; }

    [Column("ItemID")]
    public int ItemId { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("OrderItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    public virtual Order Order { get; set; }
}